name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node dependencies and build assets
        run: |
          npm install
          npm run build

      - name: Wait for file operations to complete
        run: sleep 5

      - name: Create deployment package
        run: |
          # Create deployment package with comprehensive exclusions
          tar --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='vendor' --exclude='tests' --exclude='.env' --exclude='*.tar.gz' --exclude='.gitignore' --exclude='storage/logs/*' --exclude='storage/framework/cache/*' --exclude='storage/framework/sessions/*' --exclude='storage/framework/views/*' --warning=no-file-changed -czf deployment.tar.gz .

      - name: Copy deployment package via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_SSH_HOST }}
          username: ${{ secrets.HOSTINGER_SSH_USER }}
          password: ${{ secrets.HOSTINGER_SSH_PASS }}
          port: ${{ secrets.HOSTINGER_SSH_PORT }}
          source: "deployment.tar.gz"
          target: "domains/deliumontage.com/public_html/mobile-shop-api"
          overwrite: true

      - name: Extract and deploy files
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTINGER_SSH_HOST }}
          username: ${{ secrets.HOSTINGER_SSH_USER }}
          password: ${{ secrets.HOSTINGER_SSH_PASS }}
          port: ${{ secrets.HOSTINGER_SSH_PORT }}
          script: |
            cd domains/deliumontage.com/public_html/mobile-shop-api
            
            # Remove old deployment if exists
            rm -rf *
            
            # Extract the deployment package
            tar -xzf deployment.tar.gz
            
            # Clean up the package
            rm deployment.tar.gz
            
            # Create a redirect to public directory
            echo '<?php header("Location: public/"); exit; ?>' > index.php
            
            echo "Files successfully deployed to api subdomain!"

      - name: Install dependencies and run Laravel commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTINGER_SSH_HOST }}
          username: ${{ secrets.HOSTINGER_SSH_USER }}
          password: ${{ secrets.HOSTINGER_SSH_PASS }}
          port: ${{ secrets.HOSTINGER_SSH_PORT }}
          script: |
            cd domains/deliumontage.com/public_html/mobile-shop-api
            
            # Set proper permissions
            chmod -R 755 storage
            chmod -R 755 bootstrap/cache
            
            # Install Composer dependencies
            composer install --no-dev --optimize-autoloader
            
            # Generate application key
            php artisan key:generate --force
            
            # Run database migrations
            php artisan migrate --force
            
            # Clear and cache configurations
            php artisan optimize:clear
            php artisan optimize
            
            echo "Laravel deployment completed successfully!"